---
title: "GPS-Reflectometry: The Empirical Electromagnetic Bias Estimation"
date: 2015-05-20
excerpt: "The goal of this post is to perform an empirical modeling of the L-band GNSS-R forward scattering electromagnetic bias."
mathjax: "true"

---
## 1.Introduction
  On the purpose of performing an empirical modeling of the L-band GNSS-R forward scattering electromagnetic bias, two GNSS sites located in the Gulf of Mexico were selected as the case study as shown in Figure 3.5. These two GNSS stations are collocated with a tide gauge and an anemometer, respectively, that measure sea level and wind speed. These two stations were also installed on the offshore platforms that have open views of the ocean without obstacles. Therefore, these two GNSS sites provided the perfect configurations to conduct the EM Bias modeling experiment, and able to validate the results with the two GNSS-R time series.    
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/1_1.png" alt="linearly separable data">
  
## 2.Characteristics of the GNSS Sites in the Study Region
  The Continuously Operating Reference Station (CORS) network, operated by NOAA’s National Geodetic Survey (NGS), offers an open source to access the GNSS data. The Calcasieu Pass GPS site is known as “CALC” is located at Cameron of Los Angeles, which was originally installed in April of 2013. At that time, it operated with a Trimble NetRS receiver, a geodetic-quality dual-frequency carrier phase GPS receiver. In October of 2014, Trimble NetRS was replaced with a newer Trimble receiver, the NetR9 receiver that can receive both of GPS and GLONASS signals. The Shell Beach GPS sites are known as “SBCH” is located at New Orleans. It was installed in March of 2012 with the NetRS receiver, and it was replaced with the Trimble NetR9 receiver in October of 2014. Both of their antennae have 15-s sampling rate that could generate the observation every 15s for geodetic users. As shown in the photograph (Figures in Section 1), the two stations were installed on the offshore platforms that have an open view of the water. Thus, the received multipath signals are reflected from the sea surface with no obstructions. The platforms were drilled into the seafloor bed rocks so that the positions estimated from the GPS data would be “anchored.” The GPS antennae are ~12 m and ~15 m above the mean sea surface, respectively. Both of their antennae are attached to the NOAA Tide Gauge Sentinel, so the sea surface gradient and the vertical motion could be measured regardless of the sea surface conditions.
  The Center for Operational Oceanographic Products and Services (CO-OPS), also maintained by the U.S. National Oceanic and Atmospheric Administration (NOAA) provides access to the tide gauge and wind speed data for the Calcasieu Pass and the Shell Beach stations. Digital tide gauge data at 6-minute sampling are available, each 6-minute observation represents an average of 181 1-second measurements, with additional filtering imposed by the gauge’s protective well. The anemometers are 12.25 m, and 15.58 m above mean sea surface at two GNSS sites, respectively, which can also provide 6-minute observations. These two collocated GNSS sites with high-quality observations are more than adequate for our experiments.
  
## 3.Data Processing
  This sections aims at describing our results of developing and evaluating the EM bias models, and the corresponding concise description of data processing based on the principle of GPS-R SNR method to retrieve sea level measurements. A detailed data processing will be introduced in the next chapter with additional comments. For processing of the GPS-R data using the SNR method, the broadcast ephemerides are used to calculate the satellite angles at each station. The azimuth and elevation masks are created to ensure that the reflected signals are totally from the sea surface. After detrending, the dSNR (differential SNR) passes for each station are then analyzed using the Lomb Scargle Periodograms (LSP) with an oversampling factor of 40 (resulting in a precision of 4 mm). The highest spectral power in the search window corresponds to the reflector height. In the end, the reflector heights are converted into sea level heights, and the time stamps for each sea level measurement are calculated from the mean time of the corresponding satellite pass. 
The study mainly focuses on the contribution of the SNR technique to retrieve the relevant historic coastal sea level measurements. Here, the L1 signal of GPS is selected with considering its quality and availability. L1 and L2 are the two most widely used frequency bands, observation data span for the targeted GPS station is more than 20 years long. Compared with the results from L1 signals, the sea level results from L2 SNR data are much noisier (Löfgren et al. 2015). The SNR data from L5 is better than L1 and L2, but it is only available from 2009 (Force et al., 2011). Nevertheless, integrating other different GNSS observations such as GLONASS, Galileo, Beidou, and using different frequencies such as L1, L2C, L5, if they are available, can increase the temporal resolution and the spatial resolution of the sea level time series. However, it is not capable of improving the accuracy of sea level measurements (Löfgren et al. 2015; Strandberg et al. 2016). The hourly sea level result from L1 SNR data is adequate for our study, thus only the GPS L1 signal is chosen here.
 
## 4.The Results
  The approach described in the last Section has been implemented using L1 GPS observations at the Calcasieu Pass site. An elevation mask of 2.5º~40º is used because there is no significant SNR oscillation at higher elevation angles. The range of azimuth angles is from 40º to 320º that ensured the GPS receiver could capture the reflected signal from sea surface without obstacles. For the objective of investigating the EM bias modeling, the one-year time series of sea level height for 2015 is calculated. For the demonstration, a one-week subset is selected that showed the GPS-derived sea level time series is highly correlated with tide gauge sea level time series (Figure 3.6). Since the GPS receiver can receive radar signals from more than four satellites at the same time, there are about 1-3 sea level observations per hour based on the data processing described in the last section. 
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/4_1.png" alt="linearly separable data">
  For the direct comparison and classification, the sampling rates of sea levels with wind speed observation are resampled to one hour. This procedure guaranteed that all of the observations are within the same time tags. The figures shows that the wind speed observations in January of 2015, its maximum was less than 16 m s-1. Since the number of observations larger than 10 m s-1 is inadequate, the range of wind speed values from 0 m s-1 to 10 m s-1 is thus chosen for the EM bias model computation. As the wave propagates towards the coastline, wind speed and wind direction can directly affect the wave shape. However, it is out of the scope of this study, and the use of wind direction information will be considered in future investigations.
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/4_2.png" alt="linearly separable data">
  When the tide gauge records are taken as “ground truth,” the GPS-derived sea level height residual can be calculated. the figure shows that the sea level residual with specular point distributions, which are classified by different values of wind speeds. There are about 8,000 GPS-derived sea level observations for the whole year of 2015, the number of specular points varied from 400 to 1,200 for each particular value of wind speed. For clearer illustration, the median value of sea level residuals in a 3-hour window is used in the plotting. The bin of 1 m s-1 is used to divide the wind speeds into different categories, the sea level residual with the same time tags of specific wind speed values are assigned in the same category. The sea levels residual with wind speeds from 1 m s-1 to 8 m s-1 are shown in Figure 3.8. Overall, the absolute sea level residual increases with increasing wind speeds. For the central specular points, there are no variations with changing wind speeds. On the contrary, the largest rate of sea level residual occurs on the peripheral specular points. The coordinate of the specular point is a function of azimuth and elevation angle for a specific (constant) antenna height. When the elevation angle is larger, the specular points are closer to the antenna marked by the largest white point in Figure 3.8. As each subplot shows that the sea level residual is not impacted by azimuth but increases with decreasing elevation angles. The same approach has also been used to process the GNSS-R data at the Shell Beach site. A dual-azimuth masks of 30º–120º and 210º–330º are used to avoid the jetted piles as shown in Figure 3.5c. From Figure 3.9, the characteristics of sea level residual agree well with the predicted properties from the theoretical EM bias model. That is, EM bias increases with the decreasing incidence angle and increasing wind speed.
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/4_3.png" alt="linearly separable data">
  In this study, all the sea level residual is assumed to be caused by EM bias. Thus, the least squares estimation can be employed to empirically model the EM bias using the sea level observations. The results are the resulting empirical EM bias models for the two GNSS-R sites in the Gulf of Mexico, shown in Figure 3.10 and Figure 3.11, respectively. Both empirical models are nosier than the theoretical EM bias model, probably due to limited observations and the assumption that there is only EM bias signal in the data, which is obviously not exactly correct. When the theoretical and empirical EM bias models are applied to the original GNSS-R-derived sea level data from the Calcasieu Pass, the RMS differences are reduced from 7.27 cm to 4.77 cm, and to 3.42 cm, respectively. For the Shell Beach station, the RMS differences are reduced from 7.33 cm to 4.84 cm, and to 3.36 cm when the theoretical and empirical model corrections are applied to the GNSS-R sea level measurements, respectively. We concluded that both the theoretical and the empirical EM bias models significantly improved the accuracy of GNSS-derived sea level measurements at two adjacent sites. The development of empirical EM bias models using the two nearby GNSS-R sea level data verifies the approach, and the empirical EM bias models, technically the sea state bias models (as not all signals are directly related to the GNSS EM forward scattering signals on the ocean surface creating a bias), reduced the GNSS-R sea level measurements much more than the theoretical EM bias model does.
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/4_4.png" alt="linearly separable data">
  <img src="{{ site.url }}{{ site.baseurl }}/images/gpsr_emb_empirical/4_5.png" alt="linearly separable data">
    
## 5.Discussion
  In the building of the theoretical EM bias model to correct GPS-R sea level measurements, the one-dimensional sea surfaces are generated for simplicity using the Pierson-Moskowitz and the Choppy wave models. Considering a steady wind, the Pierson-Moskowitz spectrum can realize the gravity waves in a fully developed sea surface. Since the data number cannot be infinite, the recovered variance spectrum from the generated sea surface is inconsistent with the original variance spectrum. Therefore, a large number of sea surface realization is necessary to be generated for the simulation, particularly at high wind speed. For the selection of sea surface models, Ghavidel et al. (2016) compared the Pierson–Moskowitz model with the Elfouhaily model, it shows that the largest difference of derived EM bias could be 1 cm at the wind speed of 13 m s-1 for L-band. Park et al. (2016) assessed the performances of different sea surface models. The results showed that the EM bias using the Creamer model is about two times larger than using the choppy wave model for L-band.  Hence, different sea surface models can lead to different EM bias estimation, the optimized selection of sea surface model will reduce the uncertainties of the resulting EM bias model. The first Fresnel zone is used to approximate the illuminating area by reflected GNSS signals, which is an ellipse. Thus, the two-dimensional sea surface models are more appropriate than the one-dimensional sea surface models. However, it is computationally challenging to create a large number of two-dimensional sea surface realizations. For example, Kay et al. (2011) spent 6 hours in generating one two-dimensional sea surface with 65,536×65,536 points on a 3 GHz computer.
  With the constant antenna height of 10 m, EM bias is observed to be increasing with decreasing incidence angle and increasing wind speed. The higher wind speed, to a limit, can drive higher significant wave height. Because of the non-symmetric property of sea waves, the reflected signals from sea wave crests decrease more rapidly than reflected signals from sea wave troughs with decreasing incidence angles and increasing wind speed. Therefore, the EM bias is directly proportional to the wind speed and inversely proportional to the signal reflectance incidence angles.
In the realistic data processing, the EM bias caused by antenna vertical phase center offset is estimated by minimizing the residual between selected GPS-R-derived sea level heights and tide gauge measurements. When the wind speeds were below 2 m s-1 and the incidence angles are larger than 35º, the EM bias can be considered to be negligible. These thresholds are used to select sea level heights for the EM bias model development.
  The values of the empirical EM bias model estimated using GPS-R data are larger than the values predicted by the theoretical EM bias model. One reason perhaps is that the Pierson-Moskowitz and the Choppy wave models underestimated the EM bias, and it could be verified by other hydrodynamic models. Another reason may be the empirical model consists of other elevation dependent errors. Santamaría-Gómez et al. (2015) reported an elevation dependent error below 12º that probably originated from the tropospheric refraction. Hobiger et al. (2017) also proposed estimating and modeling the troposphere errors for the GNSS-R measurements at Onsala, Sweden. Even though the EM bias is the main error source for ground-based GNSS-R, understanding and investigating other error sources could further improve its accuracy.
  
## 6.Conclusions
  In the bistatic forward-scattering GPS-R altimetry, the electromagnetic bias originates from the smaller reflectivity of wave crests than troughs that lead to underestimation of sea level heights. This Chapter first performed a numerical computation through the linear and nonlinear models to derive a theoretical EM bias model. The simulated or theoretical model showed that the EM bias increases with decreasing incidence angle and increasing wind speed. Two GPS stations with collocated tide gauge and anemometer located in the Gulf of Mexico, were selected to conduct real data analysis. The sea level residuals were calculated between GPS-R-derived sea level heights and tide gauge measurement, and divided into different values of wind speeds. Under the hypothesis that all signals of the sea level differences (between GPS-R and tide gauge) are caused by EM bias, the least squares estimation is employed to generate the empirical EM bias models at the Calcasieu Pass and the Shell Beach GNSS sites. When the theoretical and the empirical models are applied to the GPS-R derived sea levels, the RMS difference decreased from 7.3 cm to 4.8 cm and to 3.4 cm, respectively. We concluded that both EM bias models improved the accuracy of the GPS-R derived sea level, with the empirical EM bias model has the best performance. The remaining errors are possibly resulting from tropospheric refraction, other media corrections, or distorted SNR time series, and future study is warranted to further improve the GPS-R sea level accuracy. 
  
    
